-- CreateTable
CREATE TABLE "Member" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "surname" VARCHAR(50) NOT NULL,
    "mobile" INTEGER,
    "level" INTEGER NOT NULL DEFAULT 0,
    "send" INTEGER NOT NULL DEFAULT 0,
    "success" INTEGER NOT NULL DEFAULT 0,
    "achieve" INTEGER NOT NULL DEFAULT 0,
    "booking" INTEGER NOT NULL DEFAULT 0,
    "client" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Member_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Candidate" (
    "Id" SERIAL NOT NULL,
    "cv" INTEGER,
    "name" VARCHAR(50),
    "surname" VARCHAR(50),
    "email" VARCHAR(50) NOT NULL,
    "mobile" TEXT NOT NULL,
    "position" VARCHAR(50) NOT NULL,
    "age" INTEGER,
    "gender" VARCHAR(10),
    "expect" INTEGER,
    "university1" VARCHAR(100),
    "major1" VARCHAR(100),
    "gpa1" INTEGER,
    "university2" VARCHAR(100),
    "major2" VARCHAR(100),
    "gpa2" INTEGER,
    "university3" VARCHAR(100),
    "major3" VARCHAR(100),
    "gpa3" INTEGER,
    "skill" TEXT,
    "certificate" TEXT,
    "company1" TEXT,
    "from1" TIMESTAMP(3),
    "to1" TIMESTAMP(3),
    "responsibility1" TEXT,
    "leave1" TEXT,
    "company2" TEXT,
    "from2" TIMESTAMP(3),
    "to2" TIMESTAMP(3),
    "responsibility2" TEXT,
    "leave2" TEXT,
    "company3" TEXT,
    "from3" TIMESTAMP(3),
    "to3" TIMESTAMP(3),
    "responsibility3" TEXT,
    "leave3" TEXT,
    "company4" TEXT,
    "from4" TIMESTAMP(3),
    "to4" TIMESTAMP(3),
    "responsibility4" TEXT,
    "leave4" TEXT,
    "company5" TEXT,
    "from5" TIMESTAMP(3),
    "to5" TIMESTAMP(3),
    "responsibility5" TEXT,
    "leave5" TEXT,
    "company6" TEXT,
    "from6" TIMESTAMP(3),
    "to6" TIMESTAMP(3),
    "responsibility6" TEXT,
    "leave6" TEXT,
    "createDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateDate" TIMESTAMP(3),
    "updateBy" VARCHAR(50),
    "grade" VARCHAR(10),
    "score" VARCHAR(50),
    "consent" BOOLEAN NOT NULL DEFAULT true,
    "type" VARCHAR(50),
    "status" VARCHAR(100),
    "comment" TEXT,
    "booking" BOOLEAN,
    "bookingDate" TIMESTAMP(3),
    "bookingBy" VARCHAR(50),
    "startDate" TIMESTAMP(3),
    "picUrl" TEXT,

    CONSTRAINT "Candidate_pkey" PRIMARY KEY ("Id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Member_email_key" ON "Member"("email");
